services:
  mysql:
    image: mysql:8.0
    container_name: wooshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wooshop
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    container_name: wooshop-redis
    ports:
      - "6379:6379"
