spring:
  application:
    name: wooshop

  datasource:
    url: jdbc:mysql://localhost:3306/wooshop
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  jwt:
    secret: tE/rZtkrTaYMxcIY4r09eM6VlLuGn/XwlyEjWIhyGcvEo9zyNETpwQgAb7jApoNjNRgz+PawY1jF+FHM4he7tA==
    expiration: 3600000
